### ISSUE TITLE
systemd-hostnamed service failed on startup

### ISSUE THREAD

**Issue by r2d4** [coreos/minikube-iso#10]
Everything seems to be working fine, but systemd is reporting a degraded state because of the hostname service failing.

Is this a bug or limitation due to something else?

```
$ systemctl status systemd-hostnamed       
● systemd-hostnamed.service - Hostname Service
   Loaded: loaded (/lib/systemd/system/systemd-hostnamed.service; static; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2016-09-12 22:34:53 UTC; 6min ago
     Docs: man:systemd-hostnamed.service(8)
           man:hostname(5)
           man:machine-info(5)
           http://www.freedesktop.org/wiki/Software/systemd/hostnamed
  Process: 13423 ExecStart=/lib/systemd/systemd-hostnamed (code=exited, status=226/NAMESPACE)
 Main PID: 13423 (code=exited, status=226/NAMESPACE)

Sep 12 22:34:53 minikube systemd[1]: Starting Hostname Service...
Sep 12 22:34:53 minikube systemd[13423]: systemd-hostnamed.service: Failed at step NAMESPACE spawning /lib/systemd/systemd-hostnamed: No such file or directory
Sep 12 22:34:53 minikube systemd[1]: systemd-hostnamed.service: Main process exited, code=exited, status=226/NAMESPACE
Sep 12 22:34:53 minikube systemd[1]: Failed to start Hostname Service.
Sep 12 22:34:53 minikube systemd[1]: systemd-hostnamed.service: Unit entered failed state.
Sep 12 22:34:53 minikube systemd[1]: systemd-hostnamed.service: Failed with result 'exit-code'.
```

**Comment by jonboulle** [comment]
It's probably innocuous - I suppose we need to either disable the service or include the binary - @s-urbaniak ?

**Comment by s-urbaniak** [comment]
Thanks for reporting!

We don't really need this (we are setting the hostname using classical `hostname` [1]), but nevertheless it would be nice to have this working.

So `/usr/lib/systemd/system/systemd-hostnamed.service` points to the wrong location, it defines `ExecStart=/lib/systemd/systemd-hostnamed` rather than `ExecStart=/usr/lib/systemd/systemd-hostnamed` which is the correct location (and `/usr/lib/systemd/systemd-hostnamed` is present in the image.

I'll see why it generates the wrong `ExecStart` directive.

[1] https://github.com/kubernetes/minikube/blob/d74ce773cf9e6152c3bbe3bdde304e159f27ba44/vendor/github.com/docker/machine/libmachine/provision/generic.go#L41

**Comment by s-urbaniak** [comment]
I debugged a little more, it turns out, that systemd-hostnamed is started with `PrivateTmp=true`, causing the issue. I need to investigate this more.

**Comment by s-urbaniak** [comment]
bumping to next release, sorry, this needs more investigation.

**Comment by CrescendoFang** [comment]
I got same problem with Raspbian latest update:

● systemd-hostnamed.service - Hostname Service
   Loaded: loaded (/lib/systemd/system/systemd-hostnamed.service; static)
   Active: failed (Result: exit-code) since Mon 2016-10-17 20:19:47 WIB; 5min ago
     Docs: man:systemd-hostnamed.service(8)
           man:hostname(5)
           man:machine-info(5)
           http://www.freedesktop.org/wiki/Software/systemd/hostnamed
  Process: 1064 ExecStart=/lib/systemd/systemd-hostnamed (code=exited, status=226/NAMESPACE)
 Main PID: 1064 (code=exited, status=226/NAMESPACE)

**Comment by s-urbaniak** [comment]
This issue was moved to kubernetes/minikube#727
